source 'http://cat.snu.ac.kr:8000/iOS/specs.git'

target 'GAWindTemplate', :exclusive => true do
  pod "GAWindTemplate", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "GAWindTemplate", :path => "../"

  
end
