source 'https://github.com/CocoaPods/Specs.git'

target 'GAWindTemplate', :exclusive => true do
  pod "GAWindTemplate", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "GAWindTemplate", :path => "../"

  
end
